In [1]:
import tensorflow as tf
from keras.models import load_model
import pandas as pd

In [12]:
import pickle
with open(r'E:\NLP\Vietnamese-Text-Classification-master\Model NLP\BiGRU\NotConcat\X_test_noconcat.pkl', 'rb') as f:
    X_test = pickle.load(f)

In [ ]:
import pickle
with open(r'E:\NLP\Vietnamese-Text-Classification-master\Model NLP\BiGRU\NotConcat\X_test_noconcat.pkl', 'rb') as f:
    X_test = pickle.load(f)

In [13]:
X_test.shape

(45113,)

In [14]:
import pickle
with open(r'E:\NLP\Vietnamese-Text-Classification-master\Model NLP\BiGRU\NotConcat\notconcat_y.pkl', 'rb') as f:
    Y_test = pickle.load(f)


In [15]:
Y_test.shape

(45113, 26)

In [16]:
model = tf.keras.models.load_model(r"E:\NLP\Vietnamese-Text-Classification-master\Model NLP\BiGRU\Concat with Summary\results_4\model_bi_gru_news.h5", compile=False)

In [17]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [18]:
from keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences

max_words = 50000

tok = Tokenizer(num_words = max_words)

In [19]:
import numpy as np
unique_classes_test = np.unique(Y_test)
unique_classes_test

array([0., 1.], dtype=float32)

In [20]:
import numpy as np
unique_classes_test = np.unique(Y_test)
unique_classes_test

array([0., 1.], dtype=float32)

In [21]:
Y_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [20]:
X_test

135368    eu cáo_buộc công_dân nga 2 đặc_vụ đứng đầu phó...
199424    phó ban trọng_tài dương_văn_hiền tình_huống cự...
34606     sự_việc xảy chuyến bay bl529 quá_trình chuẩn_b...
189972    thất_bại 0 2 hoàng gia_lai dược nam_hà nam_địn...
189124    15 9 phạm_thị_hiền hiệu_trưởng trường mầm_non ...
                                ...                        
36611     đầu 2016 đình_chỉ hoạt_động lý_do ô_nhiễm môi_...
58147     nguyễn_hoàng_thao sinh 1963 quê_quán huyện tân...
203773    hội_nghị ban_chấp_hành vff 6 khóa 8 nhấn_mạnh ...
36658     thuê bao doanh_thu hiện_nay netflix apple_tv k...
210614    3 3 vàng a_lả chủ_tịch lđlđ tỉnh sơn_la tham_d...
Name: text, Length: 45113, dtype: object

In [23]:
print(X_test.shape)
print(Y_test.shape)

(45113, 1)
(45113, 26)


In [22]:
test_sequences = tok.texts_to_sequences(X_test)
max_len = 2000
test_sequences_matrix = pad_sequences(test_sequences,maxlen = max_len,padding='post')
score = model.evaluate(test_sequences_matrix, Y_test, verbose=0)
print(score)

y_predict = model.predict(test_sequences_matrix)

KeyboardInterrupt: 

In [ ]:
i = 0
import numpy as np
print(f"Câu test: {list(X_test)[i]}\nGiá trị dự đoán: {dict_label[str(np.argmax(y_predict[0]))]}")